# Generated by Django 4.2.3 on 2023-07-27 05:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('place', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='availability',
            options={'verbose_name': 'availability', 'verbose_name_plural': 'availability'},
        ),
    ]
