# Generated by Django 4.2.3 on 2023-07-27 06:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('place', '0003_alter_placeimage_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Perks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wifi', models.BooleanField(default=False)),
                ('workspace', models.BooleanField(default=False)),
                ('parking', models.BooleanField(default=False)),
                ('pets_allowed', models.BooleanField(default=False)),
                ('kitchen', models.BooleanField(default=False)),
                ('pool', models.BooleanField(default=False)),
                ('heating', models.BooleanField(default=False)),
                ('private_entrence', models.BooleanField(default=False)),
                ('washing_machine', models.BooleanField(default=False)),
                ('tv', models.BooleanField(default=False)),
                ('securty_camera', models.BooleanField(default=False)),
                ('air_conditioner', models.BooleanField(default=False)),
                ('place', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perks', to='place.place')),
            ],
            options={
                'verbose_name': 'perks',
                'verbose_name_plural': 'perks',
            },
        ),
    ]
